name: Render Quarto Notes

on:
  push:
    branches: [main]
    paths:
      - "notes/raw/**.qmd"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install jupyter numpy plotly pandas matplotlib

      - name: Install Quarto
        run: |
          wget https://quarto.org/download/latest/quarto-linux-amd64.deb -O quarto.deb
          sudo dpkg -i quarto.deb

      - name: Install LaTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-latex-recommended texlive-latex-extra texlive-fonts-recommended

      - name: Render all .qmd to HTML and PDF
        run: |
          mkdir -p notes/processed/html notes/processed/pdf
          find notes/raw -name "*.qmd" -print0 | xargs -0 -I {} \
            quarto render "{}" --to html --output-dir notes/processed/html
          find notes/raw -name "*.qmd" -print0 | xargs -0 -I {} \
            quarto render "{}" --to pdf --output-dir notes/processed/pdf

      - name: Upload HTML artifacts
        uses: actions/upload-artifact@v4
        with:
          name: notes-html
          path: notes/processed/html/**

      - name: Upload PDF artifacts
        uses: actions/upload-artifact@v4
        with:
          name: notes-pdfs
          path: notes/processed/pdf/*.pdf
